### ISSUE TITLE
(Real, Fake) and (Train, Test) code

### ISSUE THREAD

**Issue by wasim004** [shanface33/Deepfake_Model_Attribution#1]
Dear Sir,
Thanks for this nice work.

Can you please provide the code for splitting the dataset both for separating real,fake and train,test video files?
Thanks!

**Comment by shanface33** [comment]
Thanks for the request. The training/testing set lists have been included in the download links. Would you please attempt to download them again? Alternatively, if you could provide me with your email address, I can send the files directly to you via email.

**Comment by wasim004** [comment]
Hi,
I've already sent you an email which is provided in the 'readme' file with the dataset. I have both the test and train text files but what I mean is that I need the code to split the data based on those text files. Also can you please clarify whether the video in the dataset are only manipulated (fake) or are there real video as well?? If there are no Real videos in the dataset then DO I need to download it from somewhere else, I mean CelebDF 590 Real videos??
Thanks!

**Comment by shanface33** [comment]
Both real and Deepfake videos are included in the download link for the DFDM dataset. We named each video file in the following format: id**_id**_(scene)_(model_name).mp4. The "model name" includes both the real video (namely, with '1_original') and fake videos. 
The codes for dividing the data are not included in the dataset because we assume that it can be accomplished easily by editing the txt files. Thanks!

**Comment by wasim004** [comment]
Hi,
What this picture shows? I mean how to get the result the way you showed in the paper for each class?
Thanks!

![image](https://user-images.githubusercontent.com/24964488/233959083-3af4c529-fa64-480a-b73c-efb18a6167f4.png)

**Comment by wasim004** [comment]
Hi,
What this picture shows? I mean how to get the result the way you showed in the paper for each class?
Thanks!

![image](https://user-images.githubusercontent.com/24964488/233959083-3af4c529-fa64-480a-b73c-efb18a6167f4.png)

**Comment by shanface33** [comment]
Thanks for the feedback. Note that the model attribution performance is sensitive to frame number selection, face cropping methods, video compression, etc. In our method, we used 10 frames of each video by periodic sampling for feature learning and [Faceswap](https://github.com/deepfakes/faceswap) for face cropping (in .png format). Please refer to our paper for further information on the vulnerability of video compression. I hope this will help!
